// Exports the ABIs the frontend needs from Foundry build artifacts into app/src/generated/abis.ts.
// Run after `forge build`:  pnpm abis
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const contracts = [
  ["Pool", "Pool.sol"],
  ["PoolLens", "PoolLens.sol"],
  ["ReceiptToken", "ReceiptToken.sol"],
  ["DebtToken", "DebtToken.sol"],
  ["AssetConfig", "AssetConfig.sol"],
  ["MarketClock", "MarketClock.sol"],
  ["ProjectTokenHooks", "ProjectTokenHooks.sol"],
];

let ts = "// AUTO-GENERATED by scripts/export-abis.mjs from contracts/out. Do not edit.\n\n";
for (const [name, file] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
  ts += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
const target = join(root, "app", "src", "generated", "abis.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, ts);
console.log(`wrote ${target}`);
